package au.edu.uow.csci318.planning.infrastructure;import au.edu.uow.csci318.planning.dto.PlanningDtos.*;import com.fasterxml.jackson.databind.*;import org.apache.kafka.common.serialization.Serdes;import org.apache.kafka.streams.kstream.*;import org.springframework.context.annotation.Bean;import org.springframework.stereotype.Component;import java.time.*;import java.util.*;import java.util.concurrent.*;import java.util.function.Consumer;
@Component public class ProjectionService{private final ObjectMapper json;private final Map<UUID,AssessmentView>assessments=new ConcurrentHashMap<>();private final Map<UUID,Integer>studyMinutes=new ConcurrentHashMap<>();private final Set<UUID>seenEvents=ConcurrentHashMap.newKeySet();public ProjectionService(ObjectMapper json){this.json=json;}
 @Bean public Consumer<KStream<String,String>>workloadStream(){return input->{KStream<String,String>valid=input.filter((k,v)->accept(v,"Assessment"));valid.foreach((k,v)->captureAssessment(v));valid.selectKey((k,v)->payloadId(v)).groupByKey(Grouped.with(Serdes.String(),Serdes.String())).reduce((oldValue,newValue)->newValue,Materialized.as("assessment-latest-store")).toStream().foreach((k,v)->{});};}
 @Bean public Consumer<KStream<String,String>>studyProgressStream(){return input->{KStream<String,String>valid=input.filter((k,v)->accept(v,"StudySessionRecorded"));valid.foreach((k,v)->captureStudy(v));valid.selectKey((k,v)->payloadSubject(v)).mapValues(this::payloadMinutes).groupByKey(Grouped.with(Serdes.String(),Serdes.Integer())).reduce(Integer::sum,Materialized.as("weekly-study-minutes-store")).toStream().foreach((k,v)->{});};}
 private boolean accept(String raw,String prefix){try{JsonNode n=json.readTree(raw);UUID id=UUID.fromString(n.path("eventId").asText());return n.path("eventType").asText().startsWith(prefix)&&seenEvents.add(id);}catch(Exception e){return false;}}
 private void captureAssessment(String raw){try{AssessmentView a=json.treeToValue(json.readTree(raw).path("payload"),AssessmentView.class);assessments.put(a.id(),a);}catch(Exception ignored){}}
 private void captureStudy(String raw){try{JsonNode p=json.readTree(raw).path("payload");LocalDate date=LocalDate.parse(p.path("studyDate").asText());LocalDate monday=LocalDate.now().with(java.time.DayOfWeek.MONDAY);if(!date.isBefore(monday)&&!date.isAfter(monday.plusDays(6)))studyMinutes.merge(UUID.fromString(p.path("subjectId").asText()),p.path("durationMinutes").asInt(),Integer::sum);}catch(Exception ignored){}}
 private String payloadId(String raw){try{return json.readTree(raw).path("payload").path("id").asText();}catch(Exception e){return "invalid";}}private String payloadSubject(String raw){try{return json.readTree(raw).path("payload").path("subjectId").asText();}catch(Exception e){return "invalid";}}private Integer payloadMinutes(String raw){try{return json.readTree(raw).path("payload").path("durationMinutes").asInt();}catch(Exception e){return 0;}}
 public Collection<AssessmentView>assessments(){return List.copyOf(assessments.values());}public int studied(UUID id){return studyMinutes.getOrDefault(id,0);}
}
