package au.edu.uow.csci318.assessment.application;
import au.edu.uow.csci318.assessment.domain.Assessment;import au.edu.uow.csci318.assessment.domain.Assessment.*;import au.edu.uow.csci318.assessment.dto.AssessmentDtos.*;import au.edu.uow.csci318.assessment.infrastructure.AssessmentRepository;import org.springframework.beans.factory.annotation.Value;import org.springframework.cloud.stream.function.StreamBridge;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.client.RestClient;import java.time.*;import java.util.*;
@Service public class AssessmentApplicationService{
 private final AssessmentRepository repo;private final StreamBridge events;private final RestClient subjects;
 public AssessmentApplicationService(AssessmentRepository repo,StreamBridge events,RestClient.Builder b,@Value("${services.subject-url}")String url){this.repo=repo;this.events=events;subjects=b.baseUrl(url).build();}
 @Transactional public List<Response> importAll(ImportRequest request){verifySubject(request.subjectId());List<Response>out=new ArrayList<>();Set<String>titles=new HashSet<>();for(var c:request.assessments()){String key=c.title().trim().toLowerCase();if(!titles.add(key)||repo.existsBySubjectIdAndTitleIgnoreCase(request.subjectId(),c.title()))throw new IllegalArgumentException("Duplicate assessment: "+c.title());Integer mins=c.estimatedHours()==null?null:(int)Math.round(c.estimatedHours()*60);out.add(createInternal(new Assessment(request.subjectId(),c.title(),c.type(),c.weighting(),c.dueDate(),c.dueWeek(),c.description(),mins,Priority.MEDIUM),"AssessmentCreated"));}return out;}
 @Transactional public Response create(CreateRequest r){verifySubject(r.subjectId());if(repo.existsBySubjectIdAndTitleIgnoreCase(r.subjectId(),r.title()))throw new IllegalArgumentException("Duplicate assessment: "+r.title());return createInternal(new Assessment(r.subjectId(),r.title(),r.type(),r.weighting(),r.dueDate(),r.dueWeek(),r.description(),r.estimatedMinutes(),r.priority()),"AssessmentCreated");}
 public List<Response> all(String status,UUID subjectId){return repo.findAllByOrderByDueDateAsc().stream().filter(a->status==null||a.getStatus().name().equalsIgnoreCase(status)).filter(a->subjectId==null||a.getSubjectId().equals(subjectId)).map(this::response).toList();}
 public Response one(UUID id){return response(find(id));}
 @Transactional public Response update(UUID id,UpdateRequest r){var a=find(id);String type="AssessmentUpdated";if(r.dueDate()!=null||r.dueWeek()!=null){a.changeDeadline(r.dueDate(),r.dueWeek());type="AssessmentDeadlineChanged";}if(r.weighting()!=null)a.changeWeighting(r.weighting());if(r.estimatedMinutes()!=null){a.changeEstimatedWorkload(r.estimatedMinutes());type="AssessmentWorkloadChanged";}if(r.priority()!=null){a.changePriority(r.priority());type="AssessmentPriorityChanged";}repo.save(a);publish(type,a);return response(a);}
 @Transactional public Response complete(UUID id){var a=find(id);a.markCompleted();repo.save(a);publish("AssessmentCompleted",a);return response(a);}
 private void verifySubject(UUID id){try{subjects.get().uri("/api/subjects/{id}",id).retrieve().toBodilessEntity();}catch(Exception e){throw new DependencyException("Referenced subject does not exist or Subject Service is unavailable",e);}}
 private Response createInternal(Assessment a,String type){repo.save(a);publish(type,a);return response(a);}private Assessment find(UUID id){return repo.findById(id).orElseThrow(()->new NoSuchElementException("Assessment not found"));}
 private void publish(String type,Assessment a){events.send("assessmentEvents-out-0",new EventEnvelope(UUID.randomUUID(),type,1,Instant.now(),"assessment-service",response(a)));}
 private Response response(Assessment a){return new Response(a.getId(),a.getSubjectId(),a.getTitle(),a.getType(),a.getWeighting(),a.getDueDate(),a.getDueWeek(),a.getDescription(),a.getEstimatedMinutes(),a.getPriority(),a.getStatus(),a.getUpdatedAt());}
 public record EventEnvelope(UUID eventId,String eventType,int eventVersion,Instant eventTimestamp,String sourceService,Object payload){}
 public static class DependencyException extends RuntimeException{public DependencyException(String m,Throwable c){super(m,c);}}
}
